import streamlit as st
import pandas as pd
import plotly.express as px

# ==================================================
# PAGE CONFIGURATION
# ==================================================
st.set_page_config(
    page_title="Supermarket Analytics Dashboard",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ==================================================
# LOAD DATA
# ==================================================
@st.cache_data
def get_data():
    data = pd.read_csv("supermarket_cleaned.csv")
    data["Date"] = pd.to_datetime(data["Date"])
    return data

df = get_data()

# ==================================================
# DASHBOARD HEADER
# ==================================================
st.title("🛒 Supermarket Sales Performance & Customer Behavior Dashboard")
st.markdown("### BSMS 1306: Introduction to Data Analytics - Mini Project")
st.markdown(
    "Explore real-time data insights, retail profitability, and consumer spending patterns using the interactive filters below."
)

# ==================================================
# SIDEBAR FILTERS
# ==================================================
st.sidebar.header("🕹 Control Panel & Filters")

city_filter = st.sidebar.multiselect(
    "Select City",
    options=sorted(df["City"].unique()),
    default=df["City"].unique()
)

product_filter = st.sidebar.multiselect(
    "Select Product Line",
    options=sorted(df["Product line"].unique()),
    default=df["Product line"].unique()
)

filtered_df = df[
    (df["City"].isin(city_filter))
    &
    (df["Product line"].isin(product_filter))
]

# ==================================================
# TABS
# ==================================================
overview_tab, tab1, tab2, tab3 = st.tabs([
    "🏠 Overview",
    "🎯 Objective 1",
    "🎯 Objective 2",
    "🎯 Objective 3"
])

# ==================================================
# OVERVIEW TAB
# ==================================================
with overview_tab:

    st.subheader("📊 Key Performance Indicators (KPIs)")

    kpi_col1, kpi_col2, kpi_col3, kpi_col4 = st.columns(4)

    with kpi_col1:
        st.metric(
            "💰 Total Sales Revenue",
            f"${filtered_df['Sales'].sum():,.2f}"
        )

    with kpi_col2:
        st.metric(
            "📈 Total Gross Income",
            f"${filtered_df['Gross income'].sum():,.2f}"
        )

    with kpi_col3:
        st.metric(
            "📦 Total Quantity Sold",
            f"{filtered_df['Quantity'].sum():.0f}"
        )

    with kpi_col4:
        st.metric(
            "⭐ Average Customer Rating",
            f"{filtered_df['Rating'].mean():.2f}/10"
        )

    st.markdown("---")

    st.info(
        """
        **Objective 1**
        - Identify the most profitable product lines.
        - Evaluate contribution of each product category to total sales.

        **Objective 2**
        - Compare spending patterns between Members and Normal customers.
        - Examine spending behaviour by gender.

        **Objective 3**
        - Investigate the relationship between purchase quantity and customer ratings.
        """
    )

# ==================================================
# OBJECTIVE 1
# ==================================================
with tab1:

    st.header("🎯 Objective 1: Product Line Profitability & Contribution")

    prod_analysis = filtered_df.groupby("Product line").agg({
        "Sales": "sum",
        "Gross income": "sum"
    }).reset_index().sort_values(
        by="Gross income",
        ascending=True
    )

    obj1_col1, obj1_col2, obj1_col3 = st.columns([3,2,1])

    with obj1_col1:

        fig_prod_profit = px.bar(
            prod_analysis,
            x="Gross income",
            y="Product line",
            orientation="h",
            title="Gross Income (Profit) Generated by Product Line",
            labels={
                "Gross income": "Total Profit ($)",
                "Product line": "Product Category"
            },
            color="Gross income",
            color_continuous_scale="Turbo"
        )

        st.plotly_chart(
            fig_prod_profit,
            use_container_width=True
        )

    with obj1_col2:

        fig_prod_sales = px.pie(
            prod_analysis,
            values="Sales",
            names="Product line",
            title="Total Sales Contribution Percentage (%)",
            hole=0.4,
            color_discrete_sequence=px.colors.sequential.RdBu
        )

        st.plotly_chart(
            fig_prod_sales,
            use_container_width=True
        )
    with obj1_col3:
        st.markdown("---")
        st.info(
            """
           The horizontal bar chart and pie chart examine the profitability and sales contribution of each product line.
            """
        )            

# ==================================================
# OBJECTIVE 2
# ==================================================
with tab2:

    st.header("🎯 Objective 2: Spending Patterns by Customer Type & Gender")

    obj2_col1, obj2_col2, obj2_col3 = st.columns([3,2,1])
    with obj2_col1:

        cust_spending = filtered_df.groupby(
            "Customer type"
        )["Sales"].sum().reset_index()

        fig_cust = px.bar(
            cust_spending,
            x="Customer type",
            y="Sales",
            title="Total Spending: Members vs Normal Customers",
            labels={
                "Sales": "Total Spending ($)"
            },
            color="Customer type",
            color_discrete_sequence=[
                "#1f77b4",
                "#ff7f0e"
            ]
        )

        st.plotly_chart(
            fig_cust,
            use_container_width=True
        )

    with obj2_col2:

        gender_cust_spending = filtered_df.groupby(
            ["Customer type", "Gender"]
        )["Sales"].mean().reset_index()

        fig_gender = px.bar(
            gender_cust_spending,
            x="Customer type",
            y="Sales",
            color="Gender",
            barmode="group",
            title="Average Transaction Value by Customer Type & Gender",
            labels={
                "Sales": "Average Spend per Invoice ($)"
            },
            color_discrete_sequence=px.colors.qualitative.Pastel
        )

        st.plotly_chart(
            fig_gender,
            use_container_width=True
        )
    with obj2_col3:
        st.markdown("---")
        st.info("""
        The bar charts compare spending patterns between customer types (Members and Normal Customers) and genders.
        """)

# ==================================================
# OBJECTIVE 3
# ==================================================
with tab3:

    st.header("🎯 Objective 3: Customer Satisfaction & Purchase Behavior")

    obj3_col1, obj3_col2 = st.columns([2, 1])

    with obj3_col1:

        fig_scatter = px.scatter(
            filtered_df,
            x="Quantity",
            y="Rating",
            color="Customer type",
            title="Relationship Between Quantity Purchased and Customer Rating",
            labels={
                "Quantity": "Quantity of Products Purchased",
                "Rating": "Customer Rating (1-10)"
            },
            hover_data=[
                "Product line",
                "Sales"
            ],
            opacity=0.6,
            trendline="ols"
        )

        st.plotly_chart(
            fig_scatter,
            use_container_width=True
        )

    with obj3_col2:

        st.markdown("---")
        st.info(
            """
          The scatter plot with an OLS trendline examines the relationship between customer ratings and the quantity of products purchased.
            """
        )
